# --------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# --------------------------------------------------------------
# Dockerfile to run ONNXRuntime with source build for CPU
# Modified by Vincent Thibault to have sklearn compiled on it.

FROM ubuntu:18.04 AS builder
MAINTAINER Vincent Thibault
ADD . /code

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    aria2 \
    ca-certificates \
    g++ \
    gcc \
    git \
    make \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    && aria2c -q -d /tmp -o cmake-3.18.2-Linux-x86_64.tar.gz \
    https://github.com/Kitware/CMake/releases/download/v3.18.2/cmake-3.18.2-Linux-x86_64.tar.gz \
    && tar -zxf /tmp/cmake-3.18.2-Linux-x86_64.tar.gz --strip=1 -C /usr \
    && pip3 install --no-cache-dir \

# Prepare onnxruntime repository & build onnxruntime
RUN cd /code && /bin/bash ./build.sh --skip_submodule_sync --use_openmp --config Release --build_wheel --update --build --parallel --cmake_extra_defines ONNXRUNTIME_VERSION=$(cat ./VERSION_NUMBER) 

FROM ubuntu:18.04 AS production
COPY --from=builder /code/build/Linux/Release/dist /root
COPY --from=builder /code/dockerfiles/LICENSE-IMAGE.txt /code/LICENSE-IMAGE.txt
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.8 \
    &&
RUN apt-get update && apt-get install -y --no-install-recommends \
    libstdc++6 \
    libgomp1 \
    ca-certificates \
    python3-sklearn \
    python3-setuptools \
    python3-wheel \
    python3-pip \
    unattended-upgrades \
    && unattended-upgrade \
    && python3 -m pip install /root/*.whl \
    && rm -rf /root/*.whl \
    && python3 pip install pandas --no-cache-dir

CMD ["python3"]